// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: player.proto
#ifndef GRPC_player_2eproto__INCLUDED
#define GRPC_player_2eproto__INCLUDED

#include "player.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace player {

class Player final {
 public:
  static constexpr char const* service_full_name() {
    return "player.Player";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PlayerInfo(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::player::MapInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::player::MapInfo>> AsyncPlayerInfo(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::player::MapInfo>>(AsyncPlayerInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::player::MapInfo>> PrepareAsyncPlayerInfo(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::player::MapInfo>>(PrepareAsyncPlayerInfoRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::player::MapInfo>* AsyncPlayerInfoRaw(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::player::MapInfo>* PrepareAsyncPlayerInfoRaw(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status PlayerInfo(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::player::MapInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::player::MapInfo>> AsyncPlayerInfo(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::player::MapInfo>>(AsyncPlayerInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::player::MapInfo>> PrepareAsyncPlayerInfo(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::player::MapInfo>>(PrepareAsyncPlayerInfoRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::player::MapInfo>* AsyncPlayerInfoRaw(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::player::MapInfo>* PrepareAsyncPlayerInfoRaw(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PlayerInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PlayerInfo(::grpc::ServerContext* context, const ::player::SingePlayerInfo* request, ::player::MapInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PlayerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PlayerInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PlayerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayerInfo(::grpc::ServerContext* context, const ::player::SingePlayerInfo* request, ::player::MapInfo* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlayerInfo(::grpc::ServerContext* context, ::player::SingePlayerInfo* request, ::grpc::ServerAsyncResponseWriter< ::player::MapInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PlayerInfo<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_PlayerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PlayerInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PlayerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayerInfo(::grpc::ServerContext* context, const ::player::SingePlayerInfo* request, ::player::MapInfo* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PlayerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PlayerInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::player::SingePlayerInfo, ::player::MapInfo>(std::bind(&WithStreamedUnaryMethod_PlayerInfo<BaseClass>::StreamedPlayerInfo, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PlayerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PlayerInfo(::grpc::ServerContext* context, const ::player::SingePlayerInfo* request, ::player::MapInfo* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPlayerInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::player::SingePlayerInfo,::player::MapInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PlayerInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PlayerInfo<Service > StreamedService;
};

}  // namespace player


#endif  // GRPC_player_2eproto__INCLUDED
