// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: player.proto

#include "player.pb.h"
#include "player.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace player {

static const char* Player_method_names[] = {
  "/player.Player/PlayerInfo",
};

std::unique_ptr< Player::Stub> Player::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Player::Stub> stub(new Player::Stub(channel));
  return stub;
}

Player::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PlayerInfo_(Player_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Player::Stub::PlayerInfo(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::player::MapInfo* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PlayerInfo_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::player::MapInfo>* Player::Stub::AsyncPlayerInfoRaw(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::player::MapInfo>::Create(channel_.get(), cq, rpcmethod_PlayerInfo_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::player::MapInfo>* Player::Stub::PrepareAsyncPlayerInfoRaw(::grpc::ClientContext* context, const ::player::SingePlayerInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::player::MapInfo>::Create(channel_.get(), cq, rpcmethod_PlayerInfo_, context, request, false);
}

Player::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Player_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Player::Service, ::player::SingePlayerInfo, ::player::MapInfo>(
          std::mem_fn(&Player::Service::PlayerInfo), this)));
}

Player::Service::~Service() {
}

::grpc::Status Player::Service::PlayerInfo(::grpc::ServerContext* context, const ::player::SingePlayerInfo* request, ::player::MapInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace player

