#ifndef _Marco_H_
#define _Marco_H_

#define MAP_WIDTH 4800
#define MAP_HEIGHT 3600

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 450

#define MAP_DIVISION_X 6
#define MAP_DIVISION_Y 8

#define MAX_BEAN_NUM 4500
#define MAX_DIVISION_BEAN_NUM 100


#define MIN_EAT_MULTIPLE 1.25


#define PLAYER_INITIAL_SCORE 10
#define PLAYER_INITIAL_RADIUS 20
#define PLAYER_INITIAL_SPEED 5
#define PLAYER_MAX_DIVISION 16
#define PLAYER_MIN_DIVIDE_SCORE 20
#define PLAYER_MIN_DIVISION_DISTANCE 100
#define PLAYER_MAX_THORN_DIVISION 10
#define PLAYER_STATIC_SPEED 1.0
#define PLAYER_MOVING_COMBINE_SPEED 0.2
#define PLAYER_MIN_SPIT_SCORE 30

#define BEAN_SCORE 1
#define SPORE_SCORE 14
#define THORN_SCORE 100
#define THORN_DIVISION_SCORE 50

#define BEAN_RADIUS 8
#define SPORE_RADIUS 23
#define THORN_RADIUS 62
#define SPORE_MIN_SPIT_DISTANCE 150


#define GAME_TIME 100


#endif // !_Marco_H_

